/**
*@name          CCPM_leadTriggerHandler 
*@author        Bharath Ammanamanchi (Deloitte)
*@date          10/11/2017
*@description   This is a controller or class
*@Class         CCPM_leadTriggerHandler
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Bharath Ammanamanchi (Deloitte)    10/11/2017   Initial Implementation.
Sriraman Sridharan (Deloitte)      12/5/2017    Update Version.
Sriraman Sridharan (Deloitte)      12/15/2017   Before Update Methods. 
Sriraman Sridharan (Deloitte)      12/22/2017   After Insert Methods.
Sriraman Sridharan (Deloitte)      01/05/2018   After Update Methods.
*/
public without sharing class CCPM_leadTriggerHandlerNewOne {//implements CCPM_ITriggerHandler {
    
}