/**
*@name          CCPM_leadTriggerHandlerHelperOne 
*@author        Bharath Ammanamanchi (Deloitte)
*@date          10/20/2017
*@description   This is a helpper class for CCPM_leadTriggerHandler
*@Class         CCPM_leadTriggerHandlerHelperOne
Modification    Log:
------------------------------------------------------------------------------------
Developer                          Date         Description
------------------------------------------------------------------------------------
Bharath Ammanamanchi (Deloitte)    10/20/2017   Initial Implementation.
Sriraman Sridharan (Deloitte)       12/16/2017  Updated Version.fpopulateMessageToLeadOwnersWithinBusinessHours
*/
public without sharing class CCPM_leadTriggerHandlerHelperOne  {
    
}