/**
*@name          CCPM_leadTriggerTest_v2
*@author        Brigadesh Chandrasekar(Deloitte)
*@date          08/22/2017
@description    Test class for CCPM_lead,CCPM_leadHandler
@testClass      CCPM_leadTriggerTest_v2
Modification    Log:
------------------------------------------------------------------------------------
Developer                               Date                        Description
------------------------------------------------------------------------------------
Brigadesh Chandrasekar(Deloitte)       08/22/2017          Original Version
manjunath keshava(Deloitte)            09/19/2017          original version-test class for assignProspectLeadOwner and updateCampaignFieldResponded
*/
@istest
public class CCPM_leadTriggerTest_v2One {

}